apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
data:
  rclone.conf: |
    [s3_a]
    type = s3
    provider = Other
    endpoint = http://s3-a.example.com
    acl = private

    [s3_b]
    type = s3
    provider = Other
    endpoint = http://s3-b.example.com
    acl = private
