apiVersion: v1
kind: Secret
metadata:
  name: rclone-secret
type: Opaque
stringData:
  rclone.conf: |
    [s3_a]
    access_key_id = AKIAAAAA
    secret_access_key = XXXXXXXX

    [s3_b]
    access_key_id = AKIABBBB
    secret_access_key = YYYYYYYY
